CREATE DATABASE IF NOT EXISTS caregiver
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE caregiver;

CREATE TABLE IF NOT EXISTS attivita (
  slot INT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  ora_inizio TIME NOT NULL,
  durata INT NOT NULL,
  username VARCHAR(100) NOT NULL,
  preavviso INT DEFAULT 0,
  dove VARCHAR(255) DEFAULT NULL,
  conchi VARCHAR(255) DEFAULT NULL,
  tema VARCHAR(100) DEFAULT NULL,
  icona VARCHAR(100) DEFAULT NULL,
  data_attivita DATE NOT NULL DEFAULT CURRENT_DATE,
  ultima_modifica TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slot INT NOT NULL,
  username VARCHAR(100) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;